import { listEvents, summarizeEvents, type TelemetryEvent, type TelemetrySummary } from './telemetry.js';
import {
  calibration as learningCalibration,
  lessons as learningLessons,
  skillStats,
  type Calibration,
  type Lesson,
  type SkillStat,
} from './selfLearning.js';
import {
  normalizeAgendaNext,
  normalizeSynergyMap,
  recourseAgendaNext,
  recourseDreamStatus,
  recourseLearnStatus,
  recourseStatus,
  recourseSynergyMap,
  type AgendaNextView,
  type SynergyMapView,
} from './recourseClient.js';

/**
 * Trends & insights — a deterministic projection over two sources:
 *   1. OpenHub's unified telemetry stream (`.data/telemetry/events.jsonl`).
 *   2. Recourse's self-learning state (learn/dream/agenda/synergy).
 *
 * Nothing here is generated by a model and nothing is fabricated: each insight
 * cites the evidence that produced it, and every unavailable source is reported
 * explicitly. The output is the input to the operator-gated autonomy surface.
 */

export type InsightSeverity = 'critical' | 'high' | 'medium' | 'low' | 'info';

export interface Insight {
  id: string;
  severity: InsightSeverity;
  title: string;
  detail: string;
  systems: string[];
  evidence?: Record<string, unknown>;
}

export interface TrendPoint {
  key: string;
  count: number;
}

export interface InsightsTrends {
  windowMs: number;
  since: string;
  total: number;
  passRate: number | null;
  bySystem: TrendPoint[];
  byKind: TrendPoint[];
  byOutcome: TrendPoint[];
  bySeverity: TrendPoint[];
  /** Comparison against the immediately preceding window. */
  previousTotal: number;
  totalDelta: number;
  passRatePrevious: number | null;
  passRateDelta: number | null;
  highSeverityPrevious: number;
  highSeverityDelta: number;
}

export interface SuggestedAction {
  id: string;
  title: string;
  detail: string;
  system: 'recourse' | 'axiom';
  /** Action payload the operator can dispatch (never auto-run). */
  action: { type: string; [k: string]: unknown };
  requiresOperator: true;
}

export interface InsightsLearning {
  calibration: Calibration;
  skills: SkillStat[];
  lessons: Lesson[];
}

export interface InsightsReport {
  generatedAt: string;
  available: boolean;
  trends: InsightsTrends;
  insights: Insight[];
  learning: InsightsLearning;
  synergy: SynergyMapView & { available: boolean };
  autonomy: {
    available: boolean;
    agenda: AgendaNextView;
    learn: Record<string, unknown> | null;
    dream: Record<string, unknown> | null;
    suggestedActions: SuggestedAction[];
  };
  sources: {
    telemetry: { available: boolean; file?: string };
    recourse: { available: boolean; error?: string };
  };
}

function toPoints(map: Record<string, number>): TrendPoint[] {
  return Object.entries(map)
    .map(([key, count]) => ({ key, count }))
    .sort((a, b) => b.count - a.count || a.key.localeCompare(b.key));
}

function pickLearnState(data: any): Record<string, unknown> | null {
  const state = data && typeof data === 'object' ? data.state ?? data : null;
  if (!state || typeof state !== 'object') return null;
  return {
    ...(typeof state.selfScore === 'number' ? { selfScore: state.selfScore } : {}),
    ...(typeof state.calibrationError === 'number' ? { calibrationError: state.calibrationError } : {}),
    ...(typeof state.geneCount === 'number' ? { geneCount: state.geneCount } : {}),
    ...(Array.isArray(state.directives) ? { directives: state.directives.slice(0, 5) } : {}),
    ...(state.episode !== undefined ? { episode: state.episode } : {}),
  };
}

function rollup(events: TelemetryEvent[]): { total: number; accepted: number; rejected: number; passRate: number | null; highSeverity: number } {
  let accepted = 0;
  let rejected = 0;
  let highSeverity = 0;
  for (const e of events) {
    if (e.outcome === 'accepted') accepted += 1;
    else if (e.outcome === 'rejected') rejected += 1;
    if (e.severity === 'high' || e.severity === 'critical') highSeverity += 1;
  }
  const verdicts = accepted + rejected;
  return { total: events.length, accepted, rejected, passRate: verdicts ? accepted / verdicts : null, highSeverity };
}

export async function buildInsights(opts: { windowMs?: number } = {}): Promise<InsightsReport> {
  const windowMs = opts.windowMs && opts.windowMs > 0 ? opts.windowMs : 7 * 24 * 60 * 60 * 1000;

  const summary: TelemetrySummary = summarizeEvents({ sinceMs: windowMs });
  const events: TelemetryEvent[] = listEvents({ sinceMs: windowMs, limit: 1000 });
  // Previous window (same length, immediately before) for deltas/trends.
  const twoWindowEvents = listEvents({ sinceMs: 2 * windowMs, limit: 5000 });
  const nowMs = Date.now();
  const curStart = nowMs - windowMs;
  const prevStart = nowMs - 2 * windowMs;
  const previous = rollup(
    twoWindowEvents.filter((e) => {
      const t = Date.parse(e.at);
      return Number.isFinite(t) && t >= prevStart && t < curStart;
    }),
  );

  // OpenHub's own learner: calibrated thresholds + evidence-based lessons.
  const learning: InsightsLearning = {
    calibration: learningCalibration(),
    skills: skillStats().slice(0, 8),
    lessons: learningLessons(6),
  };

  const [status, synergy, agenda, learn, dream] = await Promise.all([
    recourseStatus(),
    recourseSynergyMap(),
    recourseAgendaNext(),
    recourseLearnStatus(),
    recourseDreamStatus(),
  ]);

  const synergyMap = normalizeSynergyMap(synergy.data);
  const agendaView = normalizeAgendaNext(agenda.data);
  const learnState = learn.available ? pickLearnState(learn.data) : null;
  const dreamState = dream.available && dream.data && typeof dream.data === 'object'
    ? (dream.data.dreamState ?? dream.data) as Record<string, unknown>
    : null;
  const recourseOnline = status.available || synergy.available || learn.available;

  const trends: InsightsTrends = {
    windowMs,
    since: summary.since,
    total: summary.total,
    passRate: summary.passRate,
    bySystem: toPoints(summary.bySystem),
    byKind: toPoints(summary.byKind),
    byOutcome: toPoints(summary.byOutcome),
    bySeverity: toPoints(summary.bySeverity),
    previousTotal: previous.total,
    totalDelta: summary.total - previous.total,
    passRatePrevious: previous.passRate,
    passRateDelta:
      summary.passRate !== null && previous.passRate !== null
        ? summary.passRate - previous.passRate
        : null,
    highSeverityPrevious: previous.highSeverity,
    highSeverityDelta: (summary.bySeverity.high ?? 0) + (summary.bySeverity.critical ?? 0) - previous.highSeverity,
  };

  const insights: Insight[] = [];
  const rejected = summary.byOutcome.rejected ?? 0;
  const accepted = summary.byOutcome.accepted ?? 0;
  // Self-tuned bar: use OpenHub's calibrated threshold once it has evidence.
  const threshold = learning.calibration.sampleSize >= 5 ? learning.calibration.passRateThreshold : 0.5;

  if (accepted + rejected > 0 && summary.passRate !== null && summary.passRate < threshold) {
    insights.push({
      id: 'pass-rate-low',
      severity: 'high',
      title: `Verified pass rate is ${Math.round(summary.passRate * 100)}% (bar ${Math.round(threshold * 100)}%)`,
      detail: `${rejected} rejected vs ${accepted} accepted verdicts in the window — dispatch informed repair rather than retrying blind. The bar is self-tuned from OpenHub's own outcome history.`,
      systems: ['axiom', 'recourse'],
      evidence: { accepted, rejected, passRate: summary.passRate, threshold, calibrationSample: learning.calibration.sampleSize },
    });
  } else if (accepted + rejected >= 5 && summary.passRate !== null && summary.passRate >= 0.8) {
    insights.push({
      id: 'pass-rate-strong',
      severity: 'info',
      title: `Verified pass rate is ${Math.round(summary.passRate * 100)}%`,
      detail: `${accepted} accepted of ${accepted + rejected} verdicts — the current skill/synergy mix is working.`,
      systems: ['axiom', 'recourse'],
      evidence: { accepted, rejected },
    });
  }

  const critical = summary.bySeverity.critical ?? 0;
  const high = summary.bySeverity.high ?? 0;
  if (critical + high > 0) {
    insights.push({
      id: 'high-severity-events',
      severity: critical > 0 ? 'critical' : 'high',
      title: `${critical + high} high/critical telemetry event${critical + high === 1 ? '' : 's'}`,
      detail: 'Recent failures or refusals crossed a severity threshold; inspect the event stream and the affected system.',
      systems: [...new Set(events.filter((e) => e.severity === 'high' || e.severity === 'critical').map((e) => e.system))],
      evidence: { critical, high },
    });
  }

  if (learnState) {
    const calibration = typeof learnState.calibrationError === 'number' ? learnState.calibrationError : null;
    const selfScore = typeof learnState.selfScore === 'number' ? learnState.selfScore : null;
    if (calibration !== null && calibration > 0.25) {
      insights.push({
        id: 'recourse-calibration',
        severity: 'medium',
        title: `Recourse calibration error ${calibration.toFixed(2)}`,
        detail: 'Its self-score is drifting from reality; trust Recourse agenda/synergy suggestions with more skepticism until it re-centers.',
        systems: ['recourse'],
        evidence: { calibrationError: calibration },
      });
    }
    if (selfScore !== null && selfScore < 0.5) {
      insights.push({
        id: 'recourse-self-score',
        severity: 'medium',
        title: `Recourse self-score ${selfScore.toFixed(2)}`,
        detail: 'The learner reports low confidence; prefer verified gates over Recourse heuristics for this window.',
        systems: ['recourse'],
        evidence: { selfScore },
      });
    }
  } else if (!recourseOnline) {
    insights.push({
      id: 'recourse-offline',
      severity: 'info',
      title: 'Recourse offline',
      detail: `No self-learning signal (${status.error ?? 'unreachable'}). Telemetry trends are still computed locally.`,
      systems: ['recourse'],
    });
  }

  if (synergyMap.candidates.length > 0) {
    insights.push({
      id: 'synergy-candidates',
      severity: 'medium',
      title: `${synergyMap.candidates.length} cross-domain transfer candidate${synergyMap.candidates.length === 1 ? '' : 's'}`,
      detail: 'Recourse has methods proven in one domain worth adapting into another; accepting even one compounds capability.',
      systems: ['recourse'],
      evidence: { candidates: synergyMap.candidates.slice(0, 5), domains: synergyMap.domains },
    });
  }

  // Self-learning insights: weak skills + self-tuned calibration, from
  // OpenHub's own recorded outcomes.
  for (const lesson of learning.lessons) {
    if (lesson.severity === 'medium' || lesson.severity === 'high') {
      insights.push({
        id: `learn:${lesson.id}`,
        severity: lesson.severity === 'high' ? 'high' : 'medium',
        title: lesson.text,
        detail: "Derived by OpenHub's own learner from recorded outcomes (skill effectiveness).",
        systems: ['self-learning', 'axiom'],
        evidence: lesson.evidence,
      });
    }
  }
  if (learning.calibration.sampleSize >= 5) {
    insights.push({
      id: 'calibration',
      severity: 'info',
      title: `Self-tuned pass-rate bar at ${Math.round(learning.calibration.passRateThreshold * 100)}%`,
      detail: `OpenHub calibrated its alerting from ${learning.calibration.sampleSize} recorded outcomes (recent pass rate ${
        learning.calibration.passRate === null ? '—' : `${Math.round(learning.calibration.passRate * 100)}%`
      }).`,
      systems: ['self-learning'],
      evidence: { ...learning.calibration },
    });
  }
  // A sharp drop is worth surfacing even when the absolute level clears the bar.
  if (trends.passRateDelta !== null && trends.passRateDelta <= -0.2 && accepted + rejected >= 3) {
    insights.push({
      id: 'pass-rate-drop',
      severity: 'medium',
      title: `Pass rate fell ${Math.abs(Math.round(trends.passRateDelta * 100))} points vs the prior window`,
      detail: 'A trend, not an absolute level — the mix regressed. Review the newest skills/findings in the event stream.',
      systems: ['axiom'],
      evidence: { current: trends.passRate, previous: trends.passRatePrevious },
    });
  }

  // Operator-gated autonomy: turn the agenda + weakest trend into concrete actions.
  const suggestedActions: SuggestedAction[] = [];
  const pushAction = (a: SuggestedAction) => {
    if (!suggestedActions.some((x) => x.id === a.id)) suggestedActions.push(a);
  };
  if (agendaView.math) {
    pushAction({
      id: 'agenda-math',
      title: `Advance Recourse milestone: ${agendaView.math.title}`,
      detail: agendaView.math.rationale ?? 'Recourse autonomous agenda head (math domain).',
      system: 'recourse',
      action: { type: 'recourse-bridge-dispatch', domain: 'math', goal: agendaView.math.title },
      requiresOperator: true,
    });
  }
  if (agendaView.oncology) {
    pushAction({
      id: 'agenda-oncology',
      title: `Advance Recourse milestone: ${agendaView.oncology.title}`,
      detail: agendaView.oncology.rationale ?? 'Recourse autonomous agenda head (oncology domain).',
      system: 'recourse',
      action: { type: 'recourse-bridge-dispatch', domain: 'oncology', goal: agendaView.oncology.title },
      requiresOperator: true,
    });
  }
  if (insights.some((i) => i.id === 'pass-rate-low')) {
    pushAction({
      id: 'repair-low-pass-rate',
      title: 'Dispatch an informed repair loop',
      detail: 'Low verified pass rate detected; run a supervised Axiom loop seeded with the failing evidence.',
      system: 'axiom',
      action: { type: 'supervision-start', goal: 'Repair the failing verified builds and raise the pass rate' },
      requiresOperator: true,
    });
  }

  return {
    generatedAt: new Date().toISOString(),
    available: true,
    trends,
    insights,
    learning,
    synergy: { available: synergy.available, ...synergyMap },
    autonomy: {
      available: recourseOnline,
      agenda: agendaView,
      learn: learnState,
      dream: dreamState,
      suggestedActions,
    },
    sources: {
      telemetry: { available: true },
      recourse: { available: recourseOnline, ...(status.error ? { error: status.error } : {}) },
    },
  };
}
